### PR TITLE
Add new icons and update old one

### PR DESCRIPTION
**Pull request by Joxit**
I added some new icons and here is the list:

indoorequal@2x

The map visual looks like this : 
image

I think `class` isn't the best place for the icon name. I found some cases where this is problematic.

For example
I added the icon `cafe`, this icon can fit for both `amenity=cafe` and `vending=coffee`.
Some classes to map
  - `bureau_de_change` => `bank`
  - `variety_store` => `shop`
  - `drinks;food` => :man_shrugging: 
  - `houseware` => `shop`
  - `locksmith` => `shop` (or new icon ?)
  - `newspapers` => `shop` (or new icon?)

### CODE REVIEW

**Comment by francois2metz** [comment]
About the use of the class/subclass for the icon name, soon we should be able to use a fallback image to try `subclass` first then the `class`. There is a bug on mapbox-gl for manually added images that prevent the use of the fallback. See https://github.com/mapbox/mapbox-gl-js/issues/9900. 
Still we may have to do a special case for vending machines. A bit tricky.

I added the missing class mapping on https://github.com/indoorequal/indoorequal/commit/c467a5ddf7b38473e3b47f5ccb2910ebe7c1ae3c and https://github.com/indoorequal/indoorequal/commit/63f4be2673a2abc4da66f3c398b9beab561fb916. 
I'll update indoorequal.org tiles in a few minutes.

**Comment by francois2metz** [comment]
The tiles on `tiles.indoorequal.org` have been updated.

**Comment by Joxit** [comment]
updated ! 22 new icons ! The full list from https://github.com/indoorequal/indoorequal/blob/63f4be2673a2abc4da66f3c398b9beab561fb916/layers/poi/class.sql#L30-L69 is available

**Comment by francois2metz** [comment]
So cool. Thanks!

**Pull request merged**
